In [5]:
#In day 3 we will learn about the arrays in the python

#list displays all type of elements where as array displays only single data type.
#if we add "Strings" in the array element then all the array elements will be converted into the strings.

import numpy as np

a = [29,26,30, True] #ths is list
a

[29, 26, 30, True]

In [6]:
print(a)

[29, 26, 30, True]


In [7]:
a = np.array(a) #this is array because it converts all the elements into strings

In [8]:
a

array([29, 26, 30,  1])

In [9]:
a

array([29, 26, 30,  1])

In [16]:
a.mean()

21.5

In [21]:
b = np.arange[0,20]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [20]:
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
b.mean()


9.5

In [29]:
m = np.reshape(b,(5,4))
print (m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
