In [91]:
#numpy creation
import numpy as np

data = np.arange(0,80)
data




array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [92]:
m = np.reshape(data,(16,5), order='F')
m

array([[ 0, 16, 32, 48, 64],
       [ 1, 17, 33, 49, 65],
       [ 2, 18, 34, 50, 66],
       [ 3, 19, 35, 51, 67],
       [ 4, 20, 36, 52, 68],
       [ 5, 21, 37, 53, 69],
       [ 6, 22, 38, 54, 70],
       [ 7, 23, 39, 55, 71],
       [ 8, 24, 40, 56, 72],
       [ 9, 25, 41, 57, 73],
       [10, 26, 42, 58, 74],
       [11, 27, 43, 59, 75],
       [12, 28, 44, 60, 76],
       [13, 29, 45, 61, 77],
       [14, 30, 46, 62, 78],
       [15, 31, 47, 63, 79]])

In [93]:
m[0,0]

0

In [94]:
#get 7
m[15,4]

79

In [95]:
type(data)

numpy.ndarray

In [96]:
data.reshape((16,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79]])

In [97]:
d1 = ['I', 'am','happy']
d2 = ['learning', 'new', 'programming']
d3 = ['programming','world','Begins']

a =np.array([d1,d2,d3])
print(a)

[['I' 'am' 'happy']
 ['learning' 'new' 'programming']
 ['programming' 'world' 'Begins']]


In [98]:
a[2,2]

'Begins'

In [99]:
type(a)

numpy.ndarray

In [100]:
a[0][2]


'happy'

In [101]:
#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

In [102]:
games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [103]:
games[1]


array([82, 57, 82, 79, 76, 72, 60, 72, 79, 80])

In [107]:
games[1][0]

82